about/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

from .views import about


urlpatterns = patterns(
    '',
    url(r'^$', about, name='about'),
    )

# EOF

blog/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

from .views import *


urlpatterns = patterns(
    '',
    url(r'^$', ArticleList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', ArticleDetail.as_view(), name='detail'),
    )

# EOF

kernel/urls.py
# coding: utf-8

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.shortcuts import redirect


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', lambda *args, **kwargs: redirect('index'), name='root'),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^imagefit/', include('imagefit.urls')),
    url(r'^search/', include('googlesearch.urls')),
    )


urlpatterns += i18n_patterns(
    '',
    url(r'^', include('main.urls')),
    url(r'^tours/', include('tour.urls', namespace='tour')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^for_partners/', include('partners.urls', namespace='partners')),
    url(r'^services/', include('services.urls', namespace='services')),
    )


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# EOF

about/models.py
# coding: utf-8

from django.db import models
from solo.models import SingletonModel
from django.utils.translation import ugettext_lazy as _
from ckeditor.fields import RichTextField
from kernel.db import PublishModel, TitleMixin, SortableMixin
from django.core.validators import MaxLengthValidator


class AboutPage(SingletonModel):
    text = RichTextField(verbose_name=_(u'Текст'), blank=True)
    
    header1 = models.CharField(
        verbose_name=_(u'Заголовок 1'),
        help_text=_(u'Наши принципы работы'),
        default=u'Наши принципы работы',
        max_length=0xff,
        blank=True,
        )
    
    princip1_img = models.ImageField(
        verbose_name=_(u'Изображение принцип-1'),
        help_text=u'100x100px',
        upload_to='about',
        blank=True,
        )
    princip1_title = models.CharField(
        verbose_name=_(u'Заголовок принцип-1'),
        help_text=_(u'Ориентация на клиента'),
        default=u'Ориентация на клиента',
        max_length=0xff,
        blank=True
        )
    princip1_description = models.TextField(
        verbose_name=_(u'Описание принцип-1'),
        help_text=_(u'Внимательное отношение и понимание потребностей клиента'),
        default=u'Внимательное отношение и понимание потребностей клиента',
        blank=True,
        )
    
    princip2_img = models.ImageField(
        verbose_name=_(u'Изображение принцип-2'),
        help_text=u'100x100px',
        upload_to='about',
        blank=True,
        )
    princip2_title = models.CharField(
        verbose_name=_(u'Заголовок принцип-2'),
        help_text=_(u'Высокое качество оказания услуг и организации туров'),
        default=u'Высокое качество оказания услуг и организации туров',
        max_length=0xff,
        blank=True
        )
    princip2_description = models.TextField(
        verbose_name=_(u'Описание принцип-2'),
        help_text=_(u'Независимо от бюджета тура, мы продумываем каждую минуту путешествия клиента'),
        default=u'Независимо от бюджета тура, мы продумываем каждую минуту путешествия клиента',
        blank=True,
        )
    
    princip3_img = models.ImageField(
        verbose_name=_(u'Изображение принцип-3'),
        help_text=u'100x100px',
        upload_to='about',
        blank=True,
        )
    princip3_title = models.CharField(
        verbose_name=_(u'Заголовок принцип-3'),
        help_text=_(u'Репутация компании'),
        default=u'Репутация компании',
        max_length=0xff,
        blank=True
        )
    princip3_description = models.TextField(
        verbose_name=_(u'Описание принцип-3'),
        help_text=_(u'Мы ценим доверие наших клиентов и партнеров'),
        default=u'Мы ценим доверие наших клиентов и партнеров',
        blank=True,
        )
    
    header2 = models.CharField(
        verbose_name=_(u'Заголовок 2'),
        help_text=_(u'Наши награды и сертификаты'),
        default=u'Наши награды и сертификаты',
        max_length=0xff,
        blank=True,
        )
    
    header3 = models.CharField(
        verbose_name=_(u'Заголовок 3'),
        help_text=_(u'Отзывы о нас'),
        default=u'Отзывы о нас',
        max_length=0xff,
        blank=True,
        )
    
    def __unicode__(self):
        return u'Страница "О Нас"'

    class Meta:
        verbose_name=_(u'Страница "О Нас"')
    
    class TMeta:
        fields = [
          'text',
          'header1',
          'header2',
          'header3',
          'princip1_img',
          'princip2_img',
          'princip3_img',
          'princip1_title',
          'princip2_title',
          'princip3_title',
          'princip1_description',
          'princip2_description',
          'princip3_description',
          ]


class Slide(PublishModel, TitleMixin, SortableMixin):
  teaser = models.TextField(
        verbose_name=_(u'Текст'),
        help_text=_(u'Рекомендуется не вводить более 250 символов'),
        blank=True,
        validators=[MaxLengthValidator(300)],
        )
  img = models.ImageField(
        verbose_name=_(u'Изображение (1280x600px)'),
        help_text=u'1280x600px',
        upload_to='about',
        blank=True,
        )
  link = models.CharField(verbose_name=_(u'Ссылка'), help_text=_(u'Кнопка "подробнее"'), max_length=0xff, blank=True)
  parent = models.ForeignKey(AboutPage, verbose_name=_(u'О нас'),)
  
  class TMeta:
      fields = [
        'is_published',
        'title',
        'teaser',
        'img',
        'link',
        ]
  
  class Meta:
        verbose_name = _(u'Слайд')
        verbose_name_plural = _(u'Слайды')
        ordering = ['weight']


class Reviews(PublishModel, SortableMixin):
  name = models.CharField(verbose_name=_(u'Имя'), max_length=0xff, blank=True)
  message = models.TextField(
        verbose_name=_(u'Текст'),
        blank=True,
        )
  img = models.ImageField(
        verbose_name=_(u'Аватар (100x100px)'),
        help_text=u'100x100px',
        upload_to='about',
        blank=True,
        )
  parent = models.ForeignKey(AboutPage, verbose_name=_(u'О нас'),)
  
  class TMeta:
      fields = [
        'is_published',
        'name',
        'message',
        'img',
        ]
      
  class Meta:
        verbose_name = _(u'Отзыв')
        verbose_name_plural = _(u'Отзывы')
        ordering = ['weight']
  
class Certificate(PublishModel, SortableMixin):
  thumb_img = models.ImageField(
        verbose_name=_(u'Превью изображения (400x560px)'),
        help_text=u'400x560px',
        upload_to='about',
        blank=True,
        )
  img = models.ImageField(
        verbose_name=_(u'Изображение (Любой размер)'),
        help_text=u'Любой размер',
        upload_to='about',
        blank=True,
        )
  parent = models.ForeignKey(AboutPage, verbose_name=_(u'О нас'),)
  
  class TMeta:
      fields = [
        'is_published',
        'thumb_img',
        'img',
        ]
  
  class Meta:
        verbose_name = _(u'Сертификат')
        verbose_name_plural = _(u'Сертификаты')
        ordering = ['weight']

about/views.py
from django.shortcuts import render
from .models import AboutPage

def about(request):
    template_name='about.html'

    return render(request, template_name, {'object': AboutPage.objects.get()})

about/templates/about.html
{% extends 'layout.html' %}
{% load static i18n %}

{% block extracss %}
  <link rel="stylesheet" href="{% static 'js/fancybox/source/jquery.fancybox.css' %}?v=2.1.5" type="text/css" media="screen" />
  <link rel="stylesheet" href="{% static 'js/fancybox/source/helpers/jquery.fancybox-buttons.css' %}?v=1.0.5" type="text/css" media="screen" />
  <link rel="stylesheet" href="{% static 'js/fancybox/source/helpers/jquery.fancybox-thumbs.css' %}?v=1.0.7" type="text/css" media="screen" />
  <link type="text/css" rel="stylesheet" href="{% static 'css/about.css' %}" media="screen">
{% endblock %}

{% block extrajs %}
  <script type="text/javascript" src="{% static 'js/fancybox/lib/jquery.mousewheel-3.0.6.pack.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/fancybox/source/jquery.fancybox.pack.js' %}?v=2.1.5"></script> 
  <script type="text/javascript" src="{% static 'js/fancybox/source/helpers/jquery.fancybox-buttons.js' %}?v=1.0.5"></script>
  <script type="text/javascript" src="{% static 'js/fancybox/source/helpers/jquery.fancybox-media.js' %}?v=1.0.6"></script>
  <script type="text/javascript" src="{% static 'js/fancybox/source/helpers/jquery.fancybox-thumbs.js' %}?v=1.0.7"></script>
  <script type="text/javascript" src="{% static 'js/about.js' %}" charset="UTF-8"></script>
{% endblock %}

{% block content %}
    <div class="top_slider content">
      <div class="container">
        <div id="slides">
          {% for slide in object.slide_set.published %}
          <div class="slider_photo">
            <p class="title">{{ slide.title|safe }}</p>
            <p class="description">{{ slide.teaser|safe }}</p>
            <div class="button_wrap">
              {% if slide.link %}
              <a href="{{ slide.link }}"><div class="button_action">{% trans 'Подробнее' %}</div></a>
              {% endif %}
            </div>
            {% if slide.img %}
            <img src="{{ slide.img.url }}">
            {% endif %}
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    
    <div class="about content">
      <div class="container">
        {{ object.text|safe }}
      </div>
    </div>
    
    <div class="our_principles content">
      <div class="container">
        <h2>{{ object.header1|safe }}</h2>
        <div class="princip">
          {% if object.princip1_img %}
          <img src="{{ object.princip1_img.url }}">
          {% endif %}
          <p class="up_p">{{ object.princip1_title|safe }}</p>
          <p class="down_p">{{ object.princip1_description|safe }}</p>
        </div>
        <div class="princip">
          {% if object.princip2_img %}
          <img src="{{ object.princip2_img.url }}">
          {% endif %}
          <p class="up_p">{{ object.princip2_title|safe }}</p>
          <p class="down_p">{{ object.princip2_description|safe }}</p>
        </div>
        <div class="princip">
          {% if object.princip3_img %}
          <img src="{{ object.princip3_img.url }}">
          {% endif %}
          <p class="up_p">{{ object.princip3_title|safe }}</p>
          <p class="down_p">{{ object.princip3_description|safe }}</p>
        </div>
        
      </div>
    </div>
    
    <div class="sertificates content">
      <div class="container">
        <h2>{{ object.header2|safe }}</h2>
        {% for cert in object.certificate_set.published %}
          <a class="fancybox" rel="group" {% if cert.img %}href="{{ cert.img.url }}"{% endif %}><img src="{% if cert.thumb_img %}{{ cert.thumb_img.url }}{% else %}{{ cert.img.url }}{% endif %}"></a>
        {% endfor %}
      </div>
    </div>
    
        <div class="feedbacks content">
      <div class="container">
        <h2>{{ object.header3|safe }}</h2>
        {% for review in object.reviews_set.published %}
        {% if forloop.counter < 4 %}
        <div class="feedback">
          {% if review.img %}<img src="{{ review.img.url }}">{% endif %}
          <div class="spell">
            <div class="spell_arrow"></div>
            <p class="feedback_name">{{ review.name }}</p>
            <p class="feedback_text">{{ review.message }}</p>
          </div>
        </div>
        {% endif %}
        {% endfor %}
        <div class="feedback_more">
          {% for review in object.reviews_set.published %}
          {% if forloop.counter > 3 %}
          <div class="feedback">
            {% if review.img %}<img src="{{ review.img.url }}">{% endif %}
            <div class="spell">
              <div class="spell_arrow"></div>
              <p class="feedback_name">{{ review.name }}</p>
              <p class="feedback_text">{{ review.message }}</p>
            </div>
          </div>
          {% endif %}
          {% endfor %}
        </div>
        <div class="button_wrap">
          <div class="button_action">{% trans 'Показать все' %}</div>
        </div>
      </div>
    </div>



    
{% endblock %}